SHARED_EXT=.bundle
LIBS= -lcrypto
DEFINES=-DPACKAGE_NAME=\"mpop3\" -DPACKAGE_TARNAME=\"mpop3\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"mpop3\ 1.0\" -DPACKAGE_BUGREPORT=\"\" -DUSE_OPENSSL=1 -DUSE_RENDEZVOUS=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DNS_SD_H=1 -DYYTEXT_POINTER=1 
CC=gcc -Wall
