SHARED_EXT=.bundle
LIBS= -lcrypto
DEFINES=-DPACKAGE_NAME=\"mpop3\" -DPACKAGE_TARNAME=\"mpop3\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"mpop3\ 1.0\" -DPACKAGE_BUGREPORT=\"\" -DUSE_OPENSSL=1 -DYYTEXT_POINTER=1 
CC=gcc -Wall
